<?php
return [
	//'url_server' => 'http://erapor-api.local:8002/api/',
	'url_server' => 'http://app.erapor-smk.net/api/',
	'table_sync' => [
		'ref.kompetensi_dasar',
		//'sekolah',
		'jurusan_sp',
		'guru',
		'rombongan_belajar',
		'peserta_didik',
		'pembelajaran',
		'ekstrakurikuler',
		'anggota_rombel',
		'dudi',
		'mou',
		'absen',
		'catatan_ppk',
		'catatan_wali',
		'deskripsi_mata_pelajaran',
		'deskripsi_sikap',
		'kd_nilai',
		'nilai',
		'nilai_akhir',
		'nilai_ekstrakurikuler',
		'nilai_sikap',
		'nilai_ukk',
		'prakerin',
		'prestasi',
		'nilai_remedial',
		'rencana_penilaian',
		'teknik_penilaian',
		'bobot_keterampilan',
		'nilai_rapor',
		'kenaikan_kelas',
		'indikator_karakter',
		'users',
		'role_user',
	],
];